#ifndef TrkAction_H
#define TrkAction_H

#include <G4UserTrackingAction.hh>

class  G4Track;

class TrkAction : public G4UserTrackingAction
{

   public:
   
      // ctor & dtor will be generated by compiler
         
      virtual void PreUserTrackingAction(const G4Track*);
      virtual void PostUserTrackingAction(const G4Track*);

};

#endif
